"""
Pydantic schema for the final Error Report (error.json).

Agent 4 output: comprehensive, machine-readable error report
with classification, evidence chain, and recommended fixes.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

from verisight.schemas.fix_schema import FixResult  # noqa: F401 — re-exported

from verisight.schemas.classification import EvidenceItem, ClassificationReasoning


class RecommendedFix(BaseModel):
    """A recommended fix action."""
    action: str = Field(description="Fix action description")
    file: str = Field(default="", description="File to modify")
    module: str = Field(default="", description="Module to modify")
    priority: str = Field(default="high", description="Priority: critical/high/medium/low")
    code_suggestion: str = Field(default="", description="Suggested code change")


class PreventionMeasure(BaseModel):
    """A future prevention measure."""
    category: str = Field(
        description="Category: assertion/coverage/lint_rule/review_checklist/process"
    )
    description: str = Field(description="Prevention measure description")
    implementation: str = Field(default="", description="How to implement")


class ErrorReport(BaseModel):
    """
    Final error report generated by Agent 4.
    Output schema for error.json — the primary deliverable.
    """
    # ─── Classification ─────────────────────────────────────────
    classification: str = Field(
        description="Root cause classification: TB Bug / RTL Bug / Spec Bug / Unknown"
    )
    module: str = Field(
        default="", description="Responsible module/component"
    )
    confidence: int = Field(
        ge=0, le=100,
        description="Confidence score (0-100%)"
    )

    # ─── Root Cause ─────────────────────────────────────────────
    root_cause: str = Field(
        description="Root cause description"
    )
    category: str = Field(
        default="",
        description="Bug category (X Propagation, Functional, CDC, Lint, etc.)"
    )
    affected_signals: List[str] = Field(
        default_factory=list,
        description="Signals affected by the bug"
    )

    # ─── References ─────────────────────────────────────────────
    simulation_timestamp: str = Field(
        default="", description="Simulation timestamp of failure"
    )
    spec_reference: str = Field(
        default="", description="Relevant specification section"
    )
    log_reference: str = Field(
        default="", description="Relevant log entry"
    )
    rtl_file: str = Field(
        default="", description="RTL file containing the bug"
    )
    rtl_line: int = Field(
        default=0, description="Line number in RTL file"
    )
    tb_file: str = Field(
        default="", description="TB file (if TB bug)"
    )

    # ─── Evidence & Reasoning ───────────────────────────────────
    evidence: List[EvidenceItem] = Field(
        default_factory=list,
        description="Evidence chain supporting the diagnosis"
    )
    reasoning: List[ClassificationReasoning] = Field(
        default_factory=list,
        description="Step-by-step reasoning chain"
    )

    # ─── Fixes & Prevention ─────────────────────────────────────
    recommended_fixes: List[RecommendedFix] = Field(
        default_factory=list,
        description="Recommended fixes"
    )
    prevention_measures: List[PreventionMeasure] = Field(
        default_factory=list,
        description="Future prevention measures"
    )

    # ─── Metadata ───────────────────────────────────────────────
    severity: str = Field(
        default="medium",
        description="Severity: critical/high/medium/low"
    )
    tags: List[str] = Field(
        default_factory=list,
        description="Tags for categorization"
    )
    session_id: str = Field(
        default="", description="Debugging session ID"
    )
    timestamp: str = Field(
        default="", description="Report generation timestamp"
    )

    # ─── Automated Fix (Agent 5) ─────────────────────────────────
    fix: Optional[FixResult] = Field(
        default=None,
        description=(
            "Automated fix proposal from Agent 5. None if fix generation "
            "was disabled, declined, or failed."
        )
    )
